function createfigure(X1, yvector1)
%CREATEFIGURE(X1, yvector1)
%  X1:  area x
%  YVECTOR1:  area yvector

%  Auto-generated by MATLAB on 08-Feb-2019 10:59:22

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create area
area(X1,yvector1,'FaceColor',[0 0.447058826684952 0.74117648601532],...
    'EdgeColor',[1 0.843137264251709 0],...
    'LineStyle','--');

box(axes1,'on');
